### ISSUE TITLE
Compiling system image error

### ISSUE THREAD

**Issue by saharbenrached** [jlapeyre/julia_project#14]
Using versions of qiskit_alt: 0.1.10 and julia_project: 0.1.23

Compiling using the command
```qiskit_alt.project.compile(calljulia="pyjulia")``` returns the following error message:
```TypeError: compile() got an unexpected keyword argument 'calljulia'```

**Comment by jlapeyre** [comment]
I erroneously suggested that `qiskit_alt.project.compile` takes the keyword argument `calljulia`. But in fact it does not.
