### ISSUE TITLE
`ensure_init()` should have an option to run in noninteractive mode

### ISSUE THREAD

**Issue by garrison** [jlapeyre/julia_project#8]
It would be nice if `ensure_init()` had an option to run in noninteractive mode.  Otherwise, I am forced to pipe `yes` to it in my Dockerfile:

https://github.com/Qiskit-Extensions/qiskit-alt/blob/dba5ed0302c78e26fe775fbae06d4a5178fdd965/Dockerfile#L19

**Comment by jlapeyre** [comment]
You can suppress all questions with environment variables. But, it might be more convenient to allow doing this in `ensure_init()` as well. One of the questions, about the depot, already can be set in `ensure_init`.
https://github.com/jlapeyre/julia_project/blob/f6c7ee8e2d33ef8fba429df3f6f029967858bb0d/julia_project/_julia_project.py#L164-L180
